# Generated by Django 2.0.6 on 2018-07-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='exame_grade',
            new_name='exam_grade',
        ),
    ]
